theme: jekyll-theme-minimal
title: NeqSim
name: Even Solbraa
email: Even.Solbraa@ntnu.no
description: An open source library for process simulation.
logo: http://folk.ntnu.no/solbraa/neqsim/NeqSim_files/image001.gif
repository: https://github.com/equinor/neqsim
