theme: jekyll-theme-minimal
title: NeqSim
name: Even Solbraa
email: Even.Solbraa@ntnu.no
description: An open source library for process simulation.
logo: figures/neqsim_logo.jpg
repository: https://github.com/equinor/neqsim
