theme: jekyll-theme-minimal
title: NeqSim
name: Even Solbraa
email: Even.Solbraa@ntnu.no
description: NeqSim is a tool for thermodynamics, physical properties and process simulation. NeqSim is available for free use and distributed as open source under the Apache-2.0 licence.
logo: figures/neqsim_logo.jpg
repository: https://github.com/equinor/neqsim
