theme: jekyll-theme-minimal
title: NeqSim
name: Even Solbraa
show_downloads: true
description: An open source library for process simulation
logo: http://folk.ntnu.no/solbraa/neqsim/NeqSim_files/image001.gif
