theme: jekyll-theme-minimal
title: NeqSim - an open source process simulator
description: NeqSim (Non-Equilibrium Simulator) is a Java library for estimation of fluid behavior and process design for oil and gas production.
