theme: jekyll-theme-minimal
description: NeqSim (Non-Equilibrium Simulator) is a Java library for estimation of fluid behavior and process design for oil and gas production.
logo: http://folk.ntnu.no/solbraa/neqsim/NeqSim_files/image001.gif
